# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 15d5a6f53d47d87c33017da9f02cdc1a9ed2cb0e9c67ed27f456f88958dc5e8f1427b5b929b6f53fb4185ae392399e0ba9b79d4f04f6c9965c3ccf0b9398de4c

test:
  secret_key_base: bd976bca23a4a09bc609f41161071b0c2292bdde99c71ece40ba2bbc2fc0040d400b1b0831ff4376b1aefa8aff75629c416e41cdbaffd7670fe73d671ae386f2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 3bbd3f537167126d1940a46a5dd8ed16f1b20dd7a9a2489e355c3283a15f368a744afc54f419fe03ec36ae706a9eb75bff27096f15912a7a3e78554ab07d64c9
